#!/bin/bash

# Script to create GitHub labels for Claude AI workflows
# Run this script after installing GitHub CLI: brew install gh

set -e

echo "🏷️  Creating GitHub labels for Claude AI workflows..."
echo ""

# Check if gh CLI is installed
if ! command -v gh &> /dev/null; then
    echo "❌ GitHub CLI (gh) is not installed."
    echo ""
    echo "Install it with:"
    echo "  macOS: brew install gh"
    echo "  Linux: https://github.com/cli/cli/blob/trunk/docs/install_linux.md"
    echo ""
    echo "After installation, authenticate with: gh auth login"
    exit 1
fi

# Check if authenticated
if ! gh auth status &> /dev/null; then
    echo "❌ Not authenticated with GitHub CLI."
    echo "Run: gh auth login"
    exit 1
fi

echo "Creating labels..."
echo ""

# Claude AI workflow labels
gh label create "refactoring" --color "5319e7" --description "Code refactoring improvements" --force
gh label create "automated" --color "bfdadc" --description "Automated changes" --force
gh label create "claude-ai" --color "7c3aed" --description "Generated by Claude AI" --force
gh label create "analysis" --color "d4c5f9" --description "Code analysis and review" --force
gh label create "weekly-report" --color "e99695" --description "Weekly refactoring report" --force
gh label create "safe-changes" --color "0e8a16" --description "Safe automated changes" --force

echo ""
echo "✅ Labels created successfully!"
echo ""
echo "Created labels:"
echo "  - refactoring (purple)"
echo "  - automated (light blue)"
echo "  - claude-ai (purple)"
echo "  - analysis (light purple)"
echo "  - weekly-report (pink)"
echo "  - safe-changes (green)"
echo ""
